version: '3.9'

services:
  database:
    image: mysql:8
    container_name: app_db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=example
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=example
    volumes:
      - my-db:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  my-db:
    driver: local
